micronaut:
  application:
    name: email
  server:
    port: 8081
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  executors:
    consumer:
      type: fixed
      nThreads: 25
datasources:
  default:
    url: ${DATABASE_URL:'jdbc:postgresql://localhost:5436/ot-bank-email'}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:pass}
    schema-generate: UPDATE
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
kafka:
  bootstrap:
    servers: ${KAFKA_ADDRESS}
jackson.serialization.writeDatesAsTimestamps: false
